Neos:
  Media:
    assetSources:
      unsplash:
        assetSource: 'DL\AssetSource\Unsplash\AssetSource\UnsplashAssetSource'
        assetSourceOptions:
          accessKey: your-access-key
          utmSource: Neos CMS Unsplash Asset Source
