Neos:
  Media:
    assetSources:
      unsplash:
        assetSource: 'DL\AssetSource\Unsplash\AssetSource\UnsplashAssetSource'
        assetSourceOptions:
          accessKey: your-access-key
          utmSource: 'Neos CMS Unsplash Asset Source https://neos.io'
          copyRightNoticeTemplate: '${"Photo by <a href=\"https://unsplash.com/" + user.username + "\">" + user.name + "</a> on <a href=\"https://unsplash.com\">Unsplash</a>"}'
